config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


	root 'homes#top'
	get 'homes/about' => 'homes#about', as: 'about'
	get 'homes/pfc_calculation' => 'homes#pfc_calculation', as: 'pfc_calculation'

	get 'users/leave' => 'users#leave', as: 'leave'
	patch 'users/hide' => 'users#hide', as: 'hide'
	resources :users, only: [:show, :index, :edit, :update]


  get 'recipes/search' => 'recipes#search', as: 'search_recipes'
  get 'recipes/input' => 'recipes#input', as: 'input_recipe'
  get 'recipes/confirm' => 'recipes#confirm', as: 'confirm_recipe'
	resources :recipes

  resources :recipe_ingredients, only: [:create, :edit, :update, :destroy]
  resources :intake_ingredients, only: [:edit, :update, :destroy]
  resources :intake_recipes, only: [:edit, :update, :destroy]

  post 'intake_ingredient' => 'intake_ingredients#create', as: 'create_intake_ingredient'

  post 'intake_recipe' => 'intake_recipes#create', as: 'create_intake_recipe'

	resources :intake_logs, only: [:index, :show]
  resources :progress_logs
  resources :ingredients
end

app/controllers/intake_logs_controller.rb
class IntakeLogsController < ApplicationController
  before_action :authenticate_user!

  def index
    @intake_dates = current_user.intake_dates.order(recorded_on: "DESC")
  end

  def show
    @intake_date = IntakeDate.find(params[:id])

    @daily_total_calorie = 0
    @daily_total_protein = 0
    @daily_total_fat = 0
    @daily_total_carbohydrate = 0

    @intake_date.intake_recipes.each do |ir|
      @daily_total_calorie += (ir.recipe.total_calorie * ir.number).round
      @daily_total_protein += (ir.recipe.protein_content * ir.number).round
      @daily_total_fat += (ir.recipe.fat_content * ir.number).round
      @daily_total_carbohydrate += (ir.recipe.carbohydrate_content * ir.number).round
    end

    @intake_date.intake_ingredients.each do |ii|
      @daily_total_calorie += (ii.ingredient.total_calorie * ii.weight/100).round
      @daily_total_protein += (ii.ingredient.protein_content * ii.weight/100).round
      @daily_total_fat += (ii.ingredient.fat_content * ii.weight/100).round
      @daily_total_carbohydrate += (ii.ingredient.carbohydrate_content * ii.weight/100).round
    end
  end

end

app/helpers/intake_logs_helper.rb
module IntakeLogsHelper
end

app/views/intake_logs/index.html.erb
<div class="intake_logs">
  <div class="grid">
    <div class="new-intake-log-box">
      <div data-turbolinks="false">
        <%= link_to "レシピから選ぶ",recipes_path, class: "btn btn-outline-dark" %>
        <%= link_to "食材から選ぶ",ingredients_path, class: "btn btn-outline-dark" %>
      </div>
    </div>
    <div class="intake-logs-box">
      <p class="box-title">カロリーログ / 一覧</p>
      <table class="table table-hover table-bordered">
        <thead>
          <tr class="active">
            <th  class="col-xs-1">日付</th>
            <th  class="col-xs-1">内容</th>
            <th  class="col-xs-1">総カロリー</th>
            <th  class="col-xs-1">詳細</th>
          </tr>
        </thead>
        <tbody>
          <% @intake_dates.each do |intake_date| %>
          <% daily_total_calorie = 0 %>
          <tr>
            <td><%= intake_date.recorded_on.strftime('%Y / %m / %d') %></td>
            <td>
              <% intake_date.intake_recipes.each do |intake_recipe| %>
              <p>・<%= intake_recipe.recipe.dish_name %>　<%= intake_recipe.number %> 食</p>

              <% intake_calorie = (intake_recipe.recipe.total_calorie*intake_recipe.number).round %>
              <% daily_total_calorie += intake_calorie%>
              <% end %>
              <% intake_date.intake_ingredients.each do |intake_ingredient| %>
              <p>・<%= intake_ingredient.ingredient.name %>　<%= intake_ingredient.weight.round %> g</p>

              <% intake_calorie = (intake_ingredient.ingredient.total_calorie*intake_ingredient.weight/100).round %>
              <% daily_total_calorie += intake_calorie%>
              <% end %>
            </td>
            <td>
              <p><%= daily_total_calorie %> kcal</p>
            </td>
            <td>
              <div data-turbolinks="false">
                <%= link_to "詳細",intake_log_path(intake_date), class: "btn btn-outline-dark" %>
              </td>
            </div>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/intake_logs/show.html.erb
<div class="intake_log_show">
  <p class="page-title"><%= @intake_date.recorded_on %>のカロリー摂取記録</p>
  <div class="grid">
    <div class="intake-info-box">
      <p class="box-title">総カロリー</p>
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <p class="box-title"><%= @daily_total_calorie %> kcal</p>
          </div>
          <div class="col-md-6">
            <p>タンパク質(p):<%= @daily_total_protein %></p>
            <p>脂質(p):<%= @daily_total_fat %></p>
            <p>炭水化物(p):<%= @daily_total_carbohydrate %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="intake-contents-box">
      <p class="box-title">食事内容</p>
      <table class="table table-hover table-bordered">
        <thead>
          <tr class="active">
            <th  class="col-xs-1">料理or食材</th>
            <th  class="col-xs-1">摂取量</th>
            <th  class="col-xs-1">カロリー</th>
            <th  class="col-xs-1"></th>
          </tr>
        </thead>
        <tbody>
          <% @intake_date.intake_recipes.each do |intake_recipe| %>
          <tr>
            <td class="p-center_v">
              <%= link_to recipe_path(intake_recipe.recipe_id) do %>
              <%= intake_recipe.recipe.dish_name %>
              <% end %>
            </td>
            <td class="p-center_v"><%= intake_recipe.number %>人前</td>
            <td class="p-center_v"><%= (intake_recipe.recipe.total_calorie*intake_recipe.number).round %> kcal</td>
            <td class="p-center">
              <%= link_to "削除",intake_recipe_path(intake_recipe),method: :delete,class: "btn btn-primary" %>
            </td>
          </tr>
          <% end %>
          <% @intake_date.intake_ingredients.each do |intake_ingredient| %>
          <tr>
            <td class="p-center_v">
              <%= link_to ingredient_path(intake_ingredient.ingredient_id) do %>
              <%= intake_ingredient.ingredient.name %>
              <% end %>
            </td>
            <td class="p-center_v"><%= intake_ingredient.weight.round %> g</td>
            <td class="p-center_v"><%= (intake_ingredient.ingredient.total_calorie*intake_ingredient.weight/100).round %> kcal</td>
            <td class="p-center">
              <%= link_to "削除",intake_ingredient_path(intake_ingredient),method: :delete,class: "btn btn-primary" %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>