config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


	root 'homes#top'
	get 'homes/about' => 'homes#about', as: 'about'
	get 'homes/pfc_calculation' => 'homes#pfc_calculation', as: 'pfc_calculation'

	get 'users/leave' => 'users#leave', as: 'leave'
	patch 'users/hide' => 'users#hide', as: 'hide'
	resources :users, only: [:show, :index, :edit, :update]


  get 'recipes/search' => 'recipes#search', as: 'search_recipes'
  get 'recipes/input' => 'recipes#input', as: 'input_recipe'
  get 'recipes/confirm' => 'recipes#confirm', as: 'confirm_recipe'
	resources :recipes

  resources :recipe_ingredients, only: [:create, :edit, :update, :destroy]
  resources :intake_ingredients, only: [:edit, :update, :destroy]
  resources :intake_recipes, only: [:edit, :update, :destroy]

  post 'intake_ingredient' => 'intake_ingredients#create', as: 'create_intake_ingredient'

  post 'intake_recipe' => 'intake_recipes#create', as: 'create_intake_recipe'

	resources :intake_logs, only: [:index, :show]
  resources :progress_logs
  resources :ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  validates :user_id, presence: true

  has_many :intake_recipes, dependent: :destroy
  has_many :recipe_ingredients, dependent: :destroy
  belongs_to :user

  attachment :dish_image

  enum creation_status:{
    食材選択: 0,
    情報入力: 1,
    内容確認: 2,
    作成完了: 3,
  }

  enum is_published: { 非公開: false, 公開: true }

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
	before_action :ensure_creating_recipe_exists, only: [:new, :input, :confirm]

	def new
		if @latest_recipe.creation_status == "食材選択"
			@ingredients = Ingredient.all
			@recipe_ingredient = RecipeIngredient.new
			@recipe_ingredients = RecipeIngredient.where(recipe_id: @latest_recipe.id)
	    # 検索用の食材データ
	    # @q = Ingredient.ransack(params[:q])
	    # @searched_ingredients=@q.result(distinct: true)
	  else
			flash[:notice] = "#{@latest_recipe.creation_status}中のレシピがあります。"
			creation_status_is
	  end
	end

	def back_new
	end

	def input
		if @latest_recipe.creation_status == "情報入力"
			@recipe_ingredients = RecipeIngredient.where(recipe_id: @latest_recipe.id)
	  else
			flash[:notice] = "#{@latest_recipe.creation_status}中のレシピがあります。"
			creation_status_is
	  end
	end

	def back_input
	end

	def confirm
		if @latest_recipe.creation_status == "内容確認"
			@recipe_ingredients = RecipeIngredient.where(recipe_id: @latest_recipe.id)
	  else
			flash[:notice] = "#{@latest_recipe.creation_status}中のレシピがあります。"
			creation_status_is
	  end
	end

	def create

	end

	def index
		@recipes = Recipe.where(creation_status: "作成完了") # where(is_published: true)
	end

	def show
    @intake_recipe = IntakeRecipe.new
    @recipe = Recipe.find(params[:id])
	end

	def edit
    @recipe = Recipe.find(params[:id])
	end

	def update
    @recipe = Recipe.find(params[:id])

    if @recipe.creation_status == "食材選択"
    	input_ingredient_information
		else
			@recipe.update(recipe_params)

			# 作成ステータスが作成完了の場合、レシピ詳細画面へ遷移
			if @recipe.creation_status == "作成完了"
				redirect_to recipe_path(@recipe)
			else
				creation_status_is
			end
		end
	end

	def destroy
		@recipe = Recipe.find(params[:id])
		@recipe.destroy
		redirect_to recipes_path
		flash[:notice] = "削除しました"
	end

	private


	def recipe_params
		params.require(:recipe).permit(
			:user_id,
			:dish_name,
			:method,
			:dish_image,
			:total_calorie,
			:protein_ratio,
			:fat_ratio,
			:carbohydrate_ratio,
			:protein_content,
			:fat_content,
			:carbohydrate_content,
			:creation_status,
			:is_published
			)
	end

	def ensure_creating_recipe_exists
		@recipes = Recipe.where(user_id: current_user.id)
		# レシピがまだ一つも投稿されていない場合はレシピを新規作成し食材選択画面にリダイレクト
		unless @recipes.exists?
			recipe = Recipe.new
			recipe.user_id = current_user.id
			recipe.save
			redirect_to new_recipe_path
		# 最新のレシピが作成完了の場合はレシピを新規作成し食材選択画面にリダイレクト
		else
			@latest_recipe = @recipes.last
			if @latest_recipe.creation_status == "作成完了"
				recipe = Recipe.new
				recipe.user_id = current_user.id
				recipe.save
				redirect_to new_recipe_path
			end
		end
	end

	# 最新レシピの制作ステータスに応じてリダイレクト先を変更
	def creation_status_is
		@recipes = Recipe.where(user_id: current_user.id)
		@latest_recipe = @recipes.last
		case @latest_recipe.creation_status
		when "食材選択"
			redirect_to new_recipe_path
		when "情報入力"
			redirect_to input_recipe_path
		when "内容確認"
			redirect_to confirm_recipe_path
		else
			flash[:alert] = "予期しないアクセスを検知しました。"
			redirect_to users_path
		end
	end

	def input_ingredient_information
		recipe_ingredients = RecipeIngredient.where(recipe_id: @recipe.id)
		if recipe_ingredients.blank?
			flash[:alert] = "食材を一つ以上選択してください。"
			redirect_to new_recipe_path
		else
			sum_protein_content = 0
			sum_fat_content = 0
			sum_carbohydrate_content = 0

			recipe_ingredients.each do |recipe_ingredient|
				use_weight = recipe_ingredient.weight/100
				sum_protein_content += recipe_ingredient.ingredient.protein_content*use_weight
				sum_fat_content += recipe_ingredient.ingredient.fat_content*use_weight
				sum_carbohydrate_content += recipe_ingredient.ingredient.carbohydrate_content*use_weight
			end

			sum_total_calorie = 4*sum_protein_content + 9*sum_fat_content + 4*sum_carbohydrate_content

			@recipe.total_calorie = sum_total_calorie
			@recipe.protein_content = sum_protein_content
			@recipe.carbohydrate_content = sum_carbohydrate_content
			@recipe.fat_content = sum_fat_content
			@recipe.protein_ratio = 100*4*sum_protein_content/sum_total_calorie
			@recipe.fat_ratio = 100*9*sum_fat_content/sum_total_calorie
			@recipe.carbohydrate_ratio = 100*4*sum_carbohydrate_content/sum_total_calorie

			@recipe.update(recipe_params)
			creation_status_is
		end
	end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/confirm.html.erb
<div class="recipes_input">
  <div class="grid">
    <div class="selected-ingredients-box">
      <p class="box-title">食材</p>
      <table class="table table-hover table-bingrediented">
        <thead>
          <tr class="active">
            <th  class="col-xs-1">食材名</th>
            <th  class="col-xs-2">グラム</th>
          </tr>
        </thead>
        <tbody>
          <% @recipe_ingredients.each do |recipe_ingredient| %>
          <tr>
            <td class="p-center_v"><%= recipe_ingredient.ingredient.name %></td>
            <td class="p-center_v"><%= recipe_ingredient.weight %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="calorie-info-box">
      <p class="box-title">1食分のカロリー成分</p>
    </div>

    <div class="recipe-input-box">
      <p class="box-title"><%= @latest_recipe.dish_name %>のレシピ</p>
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <div class="item-image">
              <%= attachment_image_tag @latest_recipe, :dish_image, class: "img-square", fallback: "no_image.jpeg", size:"250x250" %>
            </div>
          </div>
          <div class="col-md-8">
            <p>作り方</p>
            <%= @latest_recipe.method %>
          </div>
        </div>
      </div>
    </div>
  </div>

    <%= form_with model: @latest_recipe, local: true do |f| %>
    <%= f.select :is_published, Recipe.is_publisheds.keys, :selected=>@latest_recipe.is_published %>
  <div>
    <%= f.hidden_field :creation_status, :value => "作成完了" %>
    <%= f.submit 'レシピを保存する', :class => 'btn btn-outline-dark col-xs-12' , :id => 'next'%>
  </div>
    <% end %>

  <div>
    <%= form_with model: @latest_recipe, local: true do |f| %>
    <%= f.hidden_field :creation_status, :value => "情報入力" %>
    <%= f.submit '情報入力へ戻る', :class => 'col-xs-12' %>
    <% end %>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="recipes">
  <div class="one-box-colorless" data-turbolinks="false">
    <%= link_to "レシピを作成",new_recipe_path,class: "btn btn-outline-dark" %>
  </div>
  <div class="one-box">
    <div class="container">
      <p class="box-title">レシピ / 一覧</p>
      <div>
        <table class="table table-hover table-bordered">
          <thead>
            <tr class="active">
              <th  class="col-xs-1">レシピID</th>
              <th  class="col-xs-1">料理画像</th>
              <th  class="col-xs-1">料理名</th>
              <th  class="col-xs-1">調理法</th>
              <th  class="col-xs-1">総カロリー</th>
              <th  class="col-xs-1">PFCバランス</th>
              <th  class="col-xs-1"></th>
            </tr>
          </thead>
          <tbody>
            <% @recipes.each do |recipe| %>
            <tr>
              <td class="p-center_v"><%= recipe.id %></td>
              <td class="p-center_v"><%= attachment_image_tag recipe, :dish_image, :fill, 70, 70, class: "pull-left profile-img", fallback: "body_image.png", size:'70x70' %></td>
              <td class="p-center_v"><%= recipe.dish_name %></td>
              <td class="p-center_v"><%= recipe.method %></td>
              <td class="p-center_v"><%= (recipe.total_calorie).round %></td>
              <td class="p-center_v">
                <p><%= (recipe.protein_ratio).round %>%</p>
                <p><%= (recipe.fat_ratio).round %>%</p>
                <p><%= (recipe.carbohydrate_ratio).round %>%</p>
              </td>
              <td class="p-center">
                <div data-turbolinks="false">
                  <%= link_to "詳細",recipe_path(recipe),class: "btn btn-outline-dark" %>
                </div>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/recipes/input.html.erb
<div class="recipes_input">
  <%= form_with model: @latest_recipe, local: true do |f| %>
  <div class="grid">
    <div class="selected-ingredients-box">
      <p class="box-title">食材</p>
      <table class="table table-hover table-bingrediented">
        <thead>
          <tr class="active">
            <th  class="col-xs-1">食材名</th>
            <th  class="col-xs-2">グラム</th>
          </tr>
        </thead>
        <tbody>
          <% @recipe_ingredients.each do |recipe_ingredient| %>
          <tr>
            <td class="p-center_v"><%= recipe_ingredient.ingredient.name %></td>
            <td class="p-center_v"><%= recipe_ingredient.weight %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="calorie-info-box">
      <p class="box-title">1食分のカロリー成分</p>
    </div>

    <div class="recipe-input-box">
      <p class="box-title">情報入力</p>
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <div class="item-image">
              <%= attachment_image_tag @latest_recipe, :dish_image, class: "img-square", fallback: "no_image.png", size:"250x250" %>
            </div>
            <div class="form-group">
              <%= f.label :dish_image, class: "col-xs-2 control-labeltext-left" %>
              <%= f.attachment_field :dish_image %>
            </div>
          </div>
          <div class="col-md-8">
            <div class="form-group">
              <%= f.label :dish_name %>
              <%= f.text_field :dish_name, class: "validate required_dish_name form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :method %>
              <%= f.text_area :method, class: "validate required_method form-control" ,style: "height: 200px"%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= f.hidden_field :creation_status, :value => "内容確認" %>
    <%= f.submit '内容確認へ進む', :class => 'btn btn-outline-dark col-xs-12', :id => 'next' %>
  </div>

  <% end %>

  <%= form_with model: @latest_recipe, local: true do |f| %>
  <div>
    <%= f.hidden_field :creation_status, :value => "食材選択" %>
    <%= f.submit '食材選択へ戻る', :id => 'back' %>
  </div>
  <% end %>
</div>

<%= javascript_include_tag 'input_recipe.js' %>

app/views/recipes/new.html.erb
<div class="recipes_new">
  <div class="one-box">
    <div>
      <h3>レシピに追加された食材</h3>
    </div>
    <div>
      <table class="table table-hover table-bordered">
        <thead>
          <tr class="active">
            <th  class="col-xs-1">食材名</th>
            <th  class="col-xs-2">グラム</th>
            <th  class="col-xs-1">削除</th>
          </tr>
        </thead>
        <tbody>
          <% @recipe_ingredients.each do |recipe_ingredient| %>
          <tr>
            <td class="p-center_v"><%= recipe_ingredient.ingredient.name %></td>
            <td class="p-center_v">
              <%= form_with model: recipe_ingredient, local: true do |f| %>
                  <%= f.number_field :weight, step: "0.1", min: "0", class: 'form-control' %>
                  <%= f.submit 'グラムを変更', :class => 'btn btn-outline-dark col-xs-12' %>
              <% end %>
            </td>
            <td class="p-center">
              <%= link_to "削除",recipe_ingredient_path(recipe_ingredient),method: :delete,class: "btn btn-outline-dark" %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div>
    <%= form_with model: @latest_recipe, local: true do |f| %>
      <%= f.hidden_field :creation_status, :value => "情報入力" %>
      <%= f.submit '情報入力へ進む', :class => 'btn btn-outline-dark col-xs-12', :id => 'next'%>
    <% end %>
  </div>

  <div class="one-box">
    <div>
      <h3>食材一覧</h3>
    </div>

    <div>
      <table class="table table-hover table-bordered">
        <thead>
          <tr class="active">
            <th  class="col-xs-1">食材名</th>
            <th  class="col-xs-2">総カロリー</th>
            <th  class="col-xs-1">タンパク質量</th>
            <th  class="col-xs-1">脂質量</th>
            <th  class="col-xs-1">炭水化物量</th>
            <th  class="col-xs-2">PFCバランス</th>
            <th  class="col-xs-1">グラム</th>
            <th  class="col-xs-1"></th>
          </tr>
        </thead>
        <tbody>
          <% @ingredients.each do |ingredient| %>
            <%= form_with model: @recipe_ingredient, local: true do |f| %>
              <tr>
                <td class="p-center_v"><%= ingredient.name %></td>
                <td class="p-center_v"><%= ingredient.total_calorie.round %></td>
                <td class="p-center_v"><%= ingredient.protein_content.round %></td>
                <td class="p-center_v"><%= ingredient.fat_content.round %></td>
                <td class="p-center_v"><%= ingredient.carbohydrate_content.round %></td>
                <td class="p-center_v">
                  <p><%= ingredient.protein_ratio.round %>%</p>
                  <p><%= ingredient.fat_ratio.round %>%</p>
                  <p><%= ingredient.carbohydrate_ratio.round %>%</p>
                </td>
                <td class="p-center">
                  <%= f.number_field :weight, step: "1", min: "1", class: 'form-control' %>
                </td>
                <td class="p-center">
                  <%= f.hidden_field :ingredient_id, :value => ingredient.id %>
                  <%= f.submit '追加', :class => 'btn btn-outline-dark col-xs-12' %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="recipes_show">
  <div class="grid">
    <div class="add-intake-box">
      <p class="box-title">カロリーログに追加</p>
      <%= form_with url: create_intake_recipe_path, local: true do |f| %>
        <%= f.number_field :number, step: "0.1", min: "0.1", value: "1.0", class: 'form-control' %>人前
        <%= f.date_field :recorded_on, value: Date.today, class: 'form-control' %>
        <%= f.hidden_field :recipe_id, :value => @recipe.id %>
        <%= f.submit '追加', :class => 'btn btn-outline-dark col-xs-12' %>
      <% end %>
    </div>

    <div class="recipe-info-box">
      <p class="box-title"><%= @recipe.dish_name %>のレシピ</p>
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <div class="item-image">
              <%= attachment_image_tag @recipe, :dish_image, class: "img-square", fallback: "no_image.png", size:"200x200" %>
            </div>
          </div>

          <div class="col-md-6">
            <p>食材</p>
            <table class="table table-hover table-bingrediented">
              <thead>
                <tr class="active">
                  <th  class="col-xs-1">食材名</th>
                  <th  class="col-xs-2">グラム</th>
                </tr>
              </thead>
              <tbody>
                <% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
                <tr>
                  <td class="p-center_v"><%= recipe_ingredient.ingredient.name %></td>
                  <td class="p-center_v"><%= recipe_ingredient.weight %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
        <div>
      <p class="box-title">作り方</p>
          <%= @recipe.method %>
        </div>
    </div>

    <div class="calorie-info-box">
      <p class="box-title">1食分のカロリー成分</p>
    </div>


  </div>
</div>