config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


	root 'homes#top'
	get 'homes/about' => 'homes#about', as: 'about'
	get 'homes/pfc_calculation' => 'homes#pfc_calculation', as: 'pfc_calculation'

	get 'users/leave' => 'users#leave', as: 'leave'
	patch 'users/hide' => 'users#hide', as: 'hide'
	resources :users, only: [:show, :index, :edit, :update]


  get 'recipes/search' => 'recipes#search', as: 'search_recipes'
  get 'recipes/input' => 'recipes#input', as: 'input_recipe'
  get 'recipes/confirm' => 'recipes#confirm', as: 'confirm_recipe'
	resources :recipes

  resources :recipe_ingredients, only: [:create, :edit, :update, :destroy]
  resources :intake_ingredients, only: [:edit, :update, :destroy]
  resources :intake_recipes, only: [:edit, :update, :destroy]

  post 'intake_ingredient' => 'intake_ingredients#create', as: 'create_intake_ingredient'

  post 'intake_recipe' => 'intake_recipes#create', as: 'create_intake_recipe'

	resources :intake_logs, only: [:index, :show]
  resources :progress_logs
  resources :ingredients
end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	before_create :set_optional_id
	devise :database_authenticatable, :registerable,
			:recoverable, :rememberable, :validatable

  has_many :recipes, dependent: :destroy
  has_many :progress_logs, dependent: :destroy
  has_many :intake_dates, dependent: :destroy

  attribute :active_factor, :float, default: 1.2
  attribute :fat_intake_ratio, :float, default: 20


  validates :optional_id, uniqueness: true
  validates :nickname,  presence: true

	attachment :profile_image

  def active_for_authentication?
    super && (self.is_valid == true)
  end

  def lean_body_mass
    self.current_weight * (1 - self.current_body_fat/100)
  end

  def basal_metabolic_rate
    370 + 21.6 * self.lean_body_mass
  end

  def maintenance_calorie
    self.basal_metabolic_rate * self.active_factor
  end

  def calculate_daily_target_calorie
    self.maintenance_calorie - 1000 * self.weekly_target_weight
  end

	private
	def set_optional_id
		# id未設定、または、すでに同じidのレコードが存在する場合はループに入る
		while self.optional_id.blank? || User.find_by(optional_id: self.optional_id).present? do
			# ランダムな10文字をidに設定し、whileの条件検証に戻る
			self.optional_id = SecureRandom.alphanumeric(10)
		end
	end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    users_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private
  def user_params
      params.require(:user).permit(
        :nickname,
        :optional_id,
        :profile_image,
        :email,
        :is_valid,
        :initial_weight,
        :target_weight,
        :current_weight,
        :active_factor,
        :current_body_fat,
        :weekly_target_weight,
        :dairy_target_calorie,
        :protein_intake_ratio,
        :fat_intake_ratio,
        :carbohydrate_intake_ratio
      )
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :reject_user, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if (@user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false))
        flash[:alert] = "退会済みです。"
        redirect_to new_user_session_path
      end
    else
      flash[:alert] = "必須項目を入力してください。"
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  #ログイン後のリダイレクト先
  def after_sign_in_path_for(resource)
    users_path
  end
  #ログアウト後のリダイレクト先
  def after_sign_out_path_for(resource)
    root_path
end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = Recipe.where(creation_status: "作成完了",user_id: current_user.id)
    @today_intake = current_user.intake_dates.find_by(recorded_on: Date.today)

    @daily_total_calorie = 0
    @daily_total_protein = 0
    @daily_total_fat = 0
    @daily_total_carbohydrate = 0

    if @today_intake.present?
      @today_intake.intake_recipes.each do |ir|
        @daily_total_calorie += (ir.recipe.total_calorie * ir.number).round
        @daily_total_protein += (ir.recipe.protein_content * ir.number).round
        @daily_total_fat += (ir.recipe.fat_content * ir.number).round
        @daily_total_carbohydrate += (ir.recipe.carbohydrate_content * ir.number).round
      end

      @today_intake.intake_ingredients.each do |ii|
        @daily_total_calorie += (ii.ingredient.total_calorie * ii.weight/100).round
        @daily_total_protein += (ii.ingredient.protein_content * ii.weight/100).round
        @daily_total_fat += (ii.ingredient.fat_content * ii.weight/100).round
        @daily_total_carbohydrate += (ii.ingredient.carbohydrate_content * ii.weight/100).round
      end
    end

    unless current_user.daily_target_calorie.blank?
      @daily_protein_content = (current_user.daily_target_calorie * current_user.protein_intake_ratio/100) / 4
      @daily_fat_content = (current_user.daily_target_calorie * current_user.fat_intake_ratio/100) / 9
      @daily_carbohydrate_content = (current_user.daily_target_calorie * current_user.carbohydrate_intake_ratio/100) / 4
    end
  end

  def show
  end

  def edit
  end

  def update
    # 日々の目標カロリーを計算し、プロジェクトに代入
    current_user.current_weight = params[:user][:current_weight]
    current_user.target_weight = params[:user][:target_weight]
    current_user.current_body_fat = params[:user][:current_body_fat]
    current_user.active_factor = params[:user][:active_factor]
    current_user.weekly_target_weight = params[:user][:weekly_target_weight]
    calorie = current_user.calculate_daily_target_calorie
    current_user.daily_target_calorie = calorie

    #タンパク質摂取割合を計算し、プロジェクトに代入
    protein_magnification = params[:protein_magnification]
    protein_intake_content = current_user.lean_body_mass * protein_magnification.to_f
    protein_intake_ratio = (400 * protein_intake_content) / calorie
    current_user.protein_intake_ratio = protein_intake_ratio.round

    #炭水化物質摂取割合を計算し、プロジェクトに代入
    carbohydrate_intake_ratio = 80 - protein_intake_ratio.round
    current_user.carbohydrate_intake_ratio = carbohydrate_intake_ratio

    if current_user.update(user_params)
      redirect_to users_path
    else
      redirect_to edit_user_path(current_user)
      flash[:alert] = "必須項目を正しく入力してください"
    end
  end

  def leave
  end

  def hide
    current_user.update(is_valid: false)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(
      :nickname,
      :optional_id,
      :profile_image,
      :email,
      :is_valid,
      :target_weight,
      :current_weight,
      :active_factor,
      :current_body_fat,
      :weekly_target_weight,
      :daily_target_calorie,
      :protein_intake_ratio,
      :fat_intake_ratio,
      :carbohydrate_intake_ratio
      )
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="users_edit">
	<%= form_with model: current_user, url: user_path, method: :patch do |f| %>
	<div class="grid">

		<div class="required-item">
			<p class="box-title">必須項目</p>
			<div class="content">
				<h5>現在の体重</h5>
				<%= f.number_field :current_weight, step: "0.1", min: "0", class: 'form-control' %>kg
				<h5>目標体重</h5>
				<%= f.number_field :target_weight, step: "0.1", min: "0", class: 'form-control' %>kg
				<h5>現在の体脂肪率</h5>
				<%= f.number_field :current_body_fat, min: "0", max: "70", class: 'form-control' %>
			</div>
		</div>

		<div class="optional-item">
			<p class="box-title">選択項目</p>
			<h5>活動レベル</h5>
			<%= f.select :active_factor, {
				'1. 運動を全くしない、デスクワークなので仕事でも動かない(運動量レベル1.2)': 	1.2,
				'2. 週に１～２回軽い運動をする、軽めの運動(運動量レベル1.375)': 			1.375,
				'3. １週間に２～３回筋トレをする、適度にエクササイズ(運動量レベル1.55)': 	1.55,
				'4. １週間に４～５回筋トレをする、それなりにハード(運動量レベル1.725)': 		1.725,
				'5. ほぼ毎日ハードなトレーニング、肉体労働(運動量レベル1.9)': 				1.9,
			}, {}, { class: 'form-control' } %>
			<h5>一週間の目標</h5>
			<%= f.number_field :weekly_target_weight, step: "0.1", min: "0", max: "1", class: 'form-control' %>kg

			<label for="protein_magnification">タンパク質倍率：</label>
			<select id="protein_magnification" name="protein_magnification" class='form-control' >
				<option value="1">1</option>
				<option value="1.5" selected>1.5</option>
				<option value="2">2</option>
				<option value="2.5">2.5</option>
				<option value="2.5"></option>
			</select>
		</div>

		<div class="daily-intake-target-box">
			<p class="box-title">一日の摂取カロリー目標</p>
			<div id="day_limit_calorie"></div>
		</div>
	</div>

	<div>
		<%= f.submit "保存" ,:class => 'btn btn-primary'%>
	</div>
	<% end %>
</div>

<%= javascript_include_tag 'calorie_calculation.js' %>

app/views/users/index.html.erb
<div class="users">
  <div class="grid">
    <div class="user-info-box">
      <p class="box-title">ユーザー情報</p>
      <%= current_user.nickname %>
      <br>
      ID : <%= current_user.optional_id %>
      <br>
      <br>
      <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100,  class: "rounded-circle pull-left profile-img", fallback: "no_image.png", size:'100x100' %>
      <br>
      <br>
      <div class="col-xs-1"><%= link_to '会員情報を編集する', edit_user_registration_path(current_user), class: "btn btn-outline-dark" %></div>
    </div>

    <div class="progress-info-box">
      <p class="box-title">プログレス</p>
    <div class="contents">
      <p>現在体重 : <%= current_user.current_weight %> kg</p>
      <p>現在体重 : <%= current_user.target_weight %> kg</p>
      <%= link_to 'プログレス一覧を表示', progress_logs_path, class: "btn btn-outline-dark" %>
      <%= link_to 'プログレスを登録', new_progress_log_path, class: "btn btn-outline-dark" %>
    </div>
    </div>

    <div class="intake-contents-box">
      <p class="box-title">本日の食事内容</p>
      <% if @today_intake.present? %>
      <div>
        <table class="table table-hover table-bordered">
          <thead>
            <tr class="active">
              <th  class="col-xs-1">料理or食材</th>
              <th  class="col-xs-1">摂取量</th>
              <th  class="col-xs-1">カロリー</th>
            </tr>
          </thead>
          <tbody>
            <% @today_intake.intake_recipes.each do |intake_recipe| %>
            <tr>
              <td class="p-center_v">
                <%= link_to recipe_path(intake_recipe.recipe_id) do %>
                <%= intake_recipe.recipe.dish_name %>
                <% end %>
              </td>
              <td class="p-center_v"><%= intake_recipe.number %>人前</td>
              <td class="p-center_v"><%= (intake_recipe.recipe.total_calorie*intake_recipe.number).round %> kcal</td>
            </tr>
            <% end %>
            <% @today_intake.intake_ingredients.each do |intake_ingredient| %>
            <tr>
              <td class="p-center_v">
                <%= link_to ingredient_path(intake_ingredient.ingredient_id) do %>
                <%= intake_ingredient.ingredient.name %>
                <% end %>
              </td>
              <td class="p-center_v"><%= intake_ingredient.weight.round %> g</td>
              <td class="p-center_v"><%= (intake_ingredient.ingredient.total_calorie*intake_ingredient.weight/100).round %> kcal</td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <% else %>
      本日の摂取記録を追加してください。
      <% end %>
      <%= link_to 'カロリーログ一覧を表示', intake_logs_path, class: "btn btn-outline-dark" %>
    </div>

    <div class="intake-info-box">
      <p class="box-title">本日のカロリー目標</p>
      <% if current_user.daily_target_calorie.blank? %>
      一日の目標カロリーが設定されていません。
      <% else %>
      <p><%= @daily_total_calorie %> / <%= current_user.daily_target_calorie.round %> kcal</p>
      <p>タンパク質(P) : <%= @daily_total_protein %> / <%= @daily_protein_content.round %> g</p>
      <p>脂質(F) : <%= @daily_total_fat %> / <%= @daily_fat_content.round %> kcal</p>
      <p>炭水化物(C) : <%= @daily_total_carbohydrate %> / <%= @daily_carbohydrate_content.round %> g</p>
      <% end %>
      <div class="col-xs-1"data-turbolinks="false">
        <%= link_to '目標を設定する', edit_user_path(current_user), class: "btn btn-outline-dark" %>
      </div>
    </div>

    <div class="user-recipes-box">
      <p class="box-title">マイレシピ</p>
      <% @recipes.each do |recipe| %>
      <%= link_to recipe_path(recipe) do %>
      <P>・<%= recipe.dish_name %></P>
      <% end %>
      <% end %>
      <%= link_to 'もっと見る', recipes_path, class: "btn btn-outline-dark" %>
    </div>
  </div>
</div>

app/views/users/leave.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h3>本当に退会しますか？</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3">
      <%= link_to 'いいえ', users_path, class: "btn btn-primary" %>
    </div>
    <div class="col-xs-3">
      <%= link_to 'はい', hide_path, method: :patch, class: "btn btn-danger" %>
    </div>
  </div>
</div>