config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


	root 'homes#top'
	get 'homes/about' => 'homes#about', as: 'about'
	get 'homes/pfc_calculation' => 'homes#pfc_calculation', as: 'pfc_calculation'

	get 'users/leave' => 'users#leave', as: 'leave'
	patch 'users/hide' => 'users#hide', as: 'hide'
	resources :users, only: [:show, :index, :edit, :update]


  get 'recipes/search' => 'recipes#search', as: 'search_recipes'
  get 'recipes/input' => 'recipes#input', as: 'input_recipe'
  get 'recipes/confirm' => 'recipes#confirm', as: 'confirm_recipe'
	resources :recipes

  resources :recipe_ingredients, only: [:create, :edit, :update, :destroy]
  resources :intake_ingredients, only: [:edit, :update, :destroy]
  resources :intake_recipes, only: [:edit, :update, :destroy]

  post 'intake_ingredient' => 'intake_ingredients#create', as: 'create_intake_ingredient'

  post 'intake_recipe' => 'intake_recipes#create', as: 'create_intake_recipe'

	resources :intake_logs, only: [:index, :show]
  resources :progress_logs
  resources :ingredients
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

  with_options presence: true do
    validates :name, uniqueness: true
    validates :total_calorie
    validates :protein_ratio
    validates :fat_ratio
    validates :carbohydrate_ratio
    validates :protein_content
    validates :fat_content
    validates :carbohydrate_content
  end

  has_many :recipe_ingredients
  has_many :intake_ingredients

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :authenticate_user!

  def new
    @ingredient = Ingredient.new
  end

  def create
    if Ingredient.where(name: params[:ingredient][:name]).exists?
      flash[:alert] = "その名前の食材はすでに存在しています。"
      redirect_to new_ingredient_path
    else
      @ingredient = Ingredient.new(ingredient_params)

      # 総カロリー計算
      protein_calorie = 4*params[:ingredient][:protein_content].to_f
      fat_calorie = 9*params[:ingredient][:fat_content].to_f
      carbohydrate_calorie = 4*params[:ingredient][:carbohydrate_content].to_f
      total_calorie = protein_calorie + fat_calorie + carbohydrate_calorie

      # 各比率計算
      protein_ratio = 100 * protein_calorie / total_calorie
      fat_ratio = 100 * fat_calorie / total_calorie
      carbohydrate_ratio = 100 * carbohydrate_calorie / total_calorie

      @ingredient.total_calorie = total_calorie
      @ingredient.protein_ratio = protein_ratio
      @ingredient.fat_ratio = fat_ratio
      @ingredient.carbohydrate_ratio = carbohydrate_ratio
      if @ingredient.save
        redirect_to ingredients_path
      else
        redirect_to new_ingredient_path
        flash[:alert] = "すべての項目を正しく入力してください。"
      end
    end
  end

  def index
    @ingredients = Ingredient.all.order(created_at: "DESC")
  end

  def show
    @intake_ingredient = IntakeIngredient.new
    @ingredient = Ingredient.find(params[:id])
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])

    # 総カロリー計算
    protein_calorie = 4*params[:ingredient][:protein_content].to_f
    fat_calorie = 9*params[:ingredient][:fat_content].to_f
    carbohydrate_calorie = 4*params[:ingredient][:carbohydrate_content].to_f
    total_calorie = protein_calorie + fat_calorie + carbohydrate_calorie

    # 各比率計算
    protein_ratio = 100 * protein_calorie / total_calorie
    fat_ratio = 100 * fat_calorie / total_calorie
    carbohydrate_ratio = 100 * carbohydrate_calorie / total_calorie

    @ingredient.total_calorie = total_calorie
    @ingredient.protein_ratio = protein_ratio
    @ingredient.fat_ratio = fat_ratio
    @ingredient.carbohydrate_ratio = carbohydrate_ratio
    if @ingredient.update(ingredient_params)
      redirect_to ingredients_path
    else
      redirect_to edit_ingredient_path(@ingredient)
      flash[:alert] = "すべての項目を正しく入力してください。"
    end
  end

  def destroy
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(
      :name,
      :total_calorie,
      :protein_ratio,
      :fat_ratio,
      :carbohydrate_ratio,
      :protein_content,
      :fat_content,
      :carbohydrate_content)
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/edit.html.erb
<div class="container">
  <div class="row">
    <h2>食材 / 編集</h2>
    <%= form_with model: @ingredient do |f| %>
    <div class="form-group">
      <h3>食材の名前</h3>
      <%= @ingredient.name %>
    </div>
    <h2>100gあたり</h2>
    <div class="form-group">
      <%= f.label :protein_content %>
      <%= f.number_field :protein_content, step: "0.1", min: "0", class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :fat_content %>
      <%= f.number_field :fat_content, step: "0.1", min: "0", class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :carbohydrate_content %>
      <%= f.number_field :carbohydrate_content, step: "0.1", min: "0", class: 'form-control' %>
    </div>
    <div class="actions row">
      <%= f.submit '食材の情報を更新', :class => 'btn btn-primary col-xs-12' %>
    </div>
    <% end %>
    <h2>総カロリー</h2>
    <div class="row">
      <p>総カロリー</p>
      <div id="calculated_total_calorie"></div>
    </div>
  </div>
</div>

<%= javascript_include_tag 'ingredients.js' %>

app/views/ingredients/index.html.erb
<div class="ingredients">
  <div class="one-box">
    <p class="box-title">食材一覧</p>
    <div class="container">
      <div class="row">
        <table class="table table-hover table-bingrediented">
          <thead>
            <tr class="active">
              <th  class="col-xs-1">食材名</th>
              <th  class="col-xs-2">総カロリー</th>
              <th  class="col-xs-1">タンパク質量</th>
              <th  class="col-xs-1">脂質量</th>
              <th  class="col-xs-1">炭水化物量</th>
              <th  class="col-xs-2">PFCバランス</th>
            </tr>
          </thead>
          <tbody>
            <% @ingredients.each do |ingredient| %>
            <tr>
              <td class="p-center_v">
                <div data-turbolinks="false">
                  <%= link_to ingredient_path(ingredient) do %>
                  <%= ingredient.name %>
                  <% end %>
                </div>
              </td>
              <td class="p-center_v"><%= ingredient.total_calorie.round %></td>
              <td class="p-center_v"><%= ingredient.protein_content.round %></td>
              <td class="p-center_v"><%= ingredient.fat_content.round %></td>
              <td class="p-center_v"><%= ingredient.carbohydrate_content.round %></td>
              <td class="p-center_v">
                <p><%= ingredient.protein_ratio.round %>%</p>
                <p><%= ingredient.fat_ratio.round %>%</p>
                <p><%= ingredient.carbohydrate_ratio.round %>%</p>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/ingredients/new.html.erb
<div class="container">
  <div class="row">
    <h2>食材 / 登録</h2>
    <%= form_with model: @ingredient do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <h2>100gあたり</h2>
    <div class="form-group">
      <%= f.label :protein_content %>
      <%= f.number_field :protein_content, step: "0.1", min: "0", class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :fat_content %>
      <%= f.number_field :fat_content, step: "0.1", min: "0", class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :carbohydrate_content %>
      <%= f.number_field :carbohydrate_content, step: "0.1", min: "0", class: 'form-control' %>
    </div>
    <div class="actions row">
      <%= f.submit '食材情報を登録', :class => 'btn btn-primary col-xs-12' %>
    </div>
    <% end %>
    <h2>総カロリー</h2>
    <div class="row">
      <p>総カロリー</p>
      <div id="calculated_total_calorie"></div>
    </div>
  </div>
</div>

<%= javascript_include_tag 'ingredients.js' %>

app/views/ingredients/show.html.erb
<div class="ingredients_show">
  <p class="page-title">食材 <%= @ingredient.name %></p>
  <div class="grid">
    <div class="add-intake-box">
      <p class="box-title">カロリーログに追加</p>
      <div>
        <%= form_with url: create_intake_ingredient_path, local: true do |f| %>
        <%= f.number_field :weight, step: "0.1", min: "0.1", value: "1.0", class: 'form-control' %>人前
        <%= f.date_field :recorded_on, value: Date.today, class: 'form-control' %>
        <%= f.hidden_field :recipe_id, :value => @ingredient.id %>
        <%= f.submit '追加', :class => 'btn btn-outline-dark col-xs-12' %>
        <% end %>
      </div>
    </div>

    <div class="calorie-info-box">
      <p class="box-title">1食分のカロリー成分</p>
    </div>
  </div>
</div>